# Generated by Django 4.1.7 on 2023-04-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('rollnum', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('phnum', models.IntegerField(null=True)),
                ('dept', models.CharField(max_length=200, null=True)),
                ('img', models.CharField(max_length=600, null=True)),
            ],
        ),
    ]
